# This githiib action adds auto assign labels referring some keywords
name: "Issue Auto Labeling"
on:
  issues:
    types: [opened]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          title-or-body: "both"
          parameters: [ {"keywords": ["bug", "error"], "labels": ["bug"]}, {"keywords": ["doc", "document"], "labels": ["documentaion"]}]
          github-token: "${{ secrets.GITHUB_TOKEN }}"
