name: Feature Branch Workflow

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - 'feature/*' 
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pylint  # Install pylint for linting

      - name: Run pylint
        run: |
          pylint src/  # Lint your project folder, replace 'your_project' with your folder name

