name: Caller Workflow

on:
  push:
    branches:
      - main

jobs:
  use-reusable:
    uses: owner/repo/.github/workflows/feature-branch.yml@main
    with:
      input-name: value
    secrets:
      SECRET_NAME: ${{ secrets.SECRET_NAME }}
